### ISSUE TITLE
Write Background of the report

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#10]
- Base background off of "Background" section in report from last semester
- Write in full paragraphs

**Comment by computer-lov** [comment]
Beatriz completed the background of the report.

**Comment by BeatrizPer** [comment]
Night Time Parenting’s motivation and ultimate goal is to provide a solution to help ease the stressful and negative feelings that come along with taking care of an infant at night. After researching the endless struggles that new parents have to deal with when bringing in a new infant to their lives, it became evident that parents need to feel positive about caring for newborns so that they don’t get burnt out because then, the baby and parents suffer. Our company has worked on innovating an engineering design solution that enforces encouragement, peace, and equality within the parenting and child caring dynamic. Existing alternatives to solving this problem include meditation apps that help a parent follow a breathing routine to recompress. Motivational posters can be used to aid in encouragement. However, there hasn't been a system that fully integrates all these solutions into one to provide the optimal experience for the parent. Our company has taken an engineering approach to design and develop a fully integrated solution to meet the needs of parents who just need an extra helping hand.

**Comment by BeatrizPer** [comment]
Reviewed and moved to done
