### ISSUE TITLE
Write Abstract section of report

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#14]

**Comment by BeatrizPer** [comment]
Since I can't continue the UX design section until we get reviewed, I started writing a draft of the abstract based on what we discussed in class:

Taking care of a newborn at night can be very difficult for parents. The night time parenting stress from staying up all night can cause emotional problems that negatively impact a parent’s whole day and affect their own personal relationships with others. Although parenting at night is necessary, a more relaxing environment could enforce a more positive relationship with the task. To address this, we develop a wearable device that monitors stress on a user brought about during night time care through guided breathing, soothing lights and music, and encouraging messages. We hope this will make parenting a more fulfilling and less stressful experience.
