### ISSUE TITLE
Check part "liveness" for Heart Rate Sensor

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#51]
- [x] photo/schematic
- [x] code and/or instructions
- [x] expected result of "liveness" test

**Comment by BeatrizPer** [comment]
Checked that its powered on and successfully detected through I2C, added pictures/code/confirmation to report

**Comment by BeatrizPer** [comment]
Reopening issue to comment progress

**Comment by BeatrizPer** [comment]
<img width="374" alt="Screen Shot 2022-02-23 at 12 52 04 PM" src="https://user-images.githubusercontent.com/98904988/155377739-94f74dc7-1d6e-4fd4-9795-1bf01d2c77a0.png">

**Comment by BeatrizPer** [comment]
To connect the heart rate sensor and get it working, you will need the following parts.

- Heart Rate Sensor for Max 30102
- Raspberry Pi
- Jumper cables

This heart rate sensor breakout board can accept a voltage range including 3.3V, therefore the power given directly from the raspberry pi is within range to power the sensor. Because of this, no additional component is needed for power. Since the breakout board has a built-in ADC, the values are all readable. The low level schematic for the connections are seen in the figure below.

Following the image in figure 1 above, to connect the part you must first give it power. Connect the 3.3V pin on the top left of the Pi to the pin on the Max 30102 board that reads “Vin”. Then, connect a ground pin from the pi (using the bottom left in the image) and connect this with the “GND” pin on the board. Finally, since we will be using i2c to communicate, the pins for these must be wired. With another jumper cable, the GPIO 2 pin “SDA” on the pi is connected to the “SDA” pin on the Max board. The GPIO 3 pin “SCL” is then connected to the “SCL” pin on the Max board. After these four connections have been successfully created, the Max 30102 board is all wired up and ready for testing.

**Comment by BeatrizPer** [comment]
**Testing I2C Connection**
After the board is connected, the connection on I2C must be checked to verify that the Pi is reading the device properly. The steps are as follows which reference the I2C lab instructions. 

I2C must first be enabled on the Raspberry Pi OS. After logging onto the Pi, run the following command

`sudo raspi-config`

The following window will pop up as seen in figure 2. Navigate to interfacing options, select I2C and click OK.


<img width="351" alt="Screen Shot 2022-02-23 at 12 53 57 PM" src="https://user-images.githubusercontent.com/98904988/155378069-33920700-b836-4168-9dfc-276a3a8c97ba.png">


After this is done, the following window will appear confirming that you have configured the interface correctly.

<img width="415" alt="Screen Shot 2022-02-23 at 12 54 12 PM" src="https://user-images.githubusercontent.com/98904988/155378107-6b37e1e8-6934-435d-a8b7-27a1dc18bd47.png">


To verify in the program that it is enabled, run the following command.

`lsmod | grep i2c`

The following in figure 4 will be returned on the screen if the setup was successful. 

<img width="396" alt="Screen Shot 2022-02-23 at 12 54 49 PM" src="https://user-images.githubusercontent.com/98904988/155378225-596ae5a0-7f09-4bb8-a756-6ebf2fc8e892.png">

It is now time to confirm that the Max 30102 board is being read and is addressable. This will be done by scanning the entire I2C address space and looking for responses from each address. Run the following command in the terminal to do this.

`i2cdetect -y 1`


The result should be the peripheral address of the Max board. This expected value will be found in the datasheet of the part. The peripheral address is seen below in figure 5.


<img width="479" alt="Screen Shot 2022-02-23 at 12 55 23 PM" src="https://user-images.githubusercontent.com/98904988/155378334-5be06f52-cbe5-4028-b3f7-e98d026212ca.png">


The peripheral address for the Max board is 0b1010111, which in hex is equal to 0x57. Running the code from above, the expected result will be this device address present in the I2C address space. Looking at the I2C response in the terminal after running the command, the following is seen.

<img width="288" alt="Screen Shot 2022-02-23 at 12 55 55 PM" src="https://user-images.githubusercontent.com/98904988/155378420-b1ceaf75-3c82-4df1-9b61-d548c6d6d442.png">

As expected, the peripheral address for our board is seen at 0x57 which is what it should be according to the datasheet. This confirms that our part is successfully connected through I2C and ready to read values.

**Comment by BeatrizPer** [comment]
working and done
