### ISSUE TITLE
Wireframe for physical product UI

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#61]

**Comment by BeatrizPer** [comment]
Adjusting Wrireframe based on feedback

- add SOS button to call for other caretaker
- change LED screen to also show wakeup time, current time, bpm
- change buttons to dials so easily and quickly change setting for brightness/noise

**Comment by BeatrizPer** [comment]
Asking team for feedback

**Comment by computer-lov** [comment]
Reviewed and moving to done.

**Comment by BeatrizPer** [comment]
@ffund 
Can you review our updated UI after making adjustments from your feedback

**Comment by ffund** [comment]
@BeatrizPer 

We discussed the option of changing to a "lights on/off" button instead of a brightness dial. In that case, what is the layout of the "lights" button vs "SoS" button - where do those both go? (you want to make sure that it's not easy to accidentally trigger the SoS when user meant to turn light off".

Actually, it seems to me that the user might want to adjust brightness of the LED bar graph. Perhaps you should keep the brightness dial for adjusting the LED, and have it to turn display off if the brightness dial is set at the far (low) end.

**Comment by BeatrizPer** [comment]
Updated wireframe
<img width="888" alt="Screen Shot 2022-05-10 at 12 57 05 PM" src="https://user-images.githubusercontent.com/98904988/167682486-80d87ad2-1786-4bd2-b7d6-11186cbf9871.png">
